docs_dir: book
site_name: Python for experienced programmers
theme:
    name: material
nav:
    - "1. Introduction": 'index.md'
    - "2. Meta": 'meta.md'
    - "3. Data Types": 'data-types.md'

markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - meta
    - toc:
        permalink: true